# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

python_script:

# Text to speech
tts:
  - platform: google_translate

# Includes
automation: !include_dir_merge_list automation/
# device_tracker: !include_dir_merge_list device_tracker/
#group: !include_dir_merge_list group/
light: !include_dir_merge_list group/light
input_number: !include_dir_merge_named input_number/
input_boolean: !include_dir_merge_named input_boolean/
#input_text: !include_dir_merge_named input_text/
#scene: !include scene.yaml
#script: !include script.yaml
sensor: !include sensor.yaml
#shell_command: !include shell_command.yaml
homeassistant:
  customize: !include customize.yaml

logger:
  default: info

lovelace:
  mode: yaml
