title: Home
views:
  - path: default_view
    title: Home
    badges:
      - entity: binary_sensor.updater
      - entity: person.val
      - entity: sensor.time
      - entity: sun.sun
    cards:
      - type: entities
        title: Light rooms
        entities:
          - light.bedroom_lights
          - light.living_room_lights
        show_header_toggle: true
      - type: entities
        title: Light bulbs
        entities:
          - light.zha_bedroom_deckenfluter
          - light.zha_bedroom_desk
          - light.zha_living_room_deckenfluter
          - light.bathroom_left
          - light.bathroom_right
      - type: weather-forecast
        name: Forecast
        entity: weather.home
      - type: entities
        title: Button battery levels
        entities:
          - input_boolean.enable_battery_alarm
          - input_number.warn_battery_level
          - input_number.crit_battery_level
          - sensor.smart_button_bedroom_battery_level
          - sensor.smart_button_living_room_battery_level
          - sensor.smart_button_bathroom_battery_level
      - type: entities
        title: Time/Date
        entities:
          - sensor.date_time
          - sensor.date_time_utc
        show_header_toggle: true
      - type: entities
        title: Wakeup light
        entities:
          - input_boolean.wakeup
          - input_boolean.wakeup_weekends
          - input_boolean.wakeup_only_when_home
          - input_number.wakeup_hour
          - input_number.wakeup_minutes
          - input_number.wakeup_duration
          - input_number.wakeup_final_brightness
          - sensor.wakeup_alarm_time
          - sensor.wakeup_start_time_lights
          - sensor.wakeup_fadein_duration
        show_header_toggle: false
      - type: entities
        title: Notifications
        entities:
          - input_boolean.enable_version_notification
          - input_boolean.enable_battery_alarm
