- alias: 'Turn lights on when my devices are in home zone'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: person.val
    to: home
  action:
    service: light.turn_on
    entity_id:
      - light.bedroom
      - light.living_room
      - light.bathroom

- alias: 'Turn lights off when my devices are not in home zone'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: person.val
    to: not_home
  action:
    service: light.turn_off
    entity_id:
      - light.bedroom
      - light.living_room
      - light.bathroom
