- alias: 'Smart button storage dim down'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.dim_state_storage_stop
      from: "on"
      to: "off"
  condition:
    condition: state
    entity_id: input_boolean.dim_state_storage_up
    state: 'off'
  action:
    repeat:
      sequence:
        - service: light.turn_on
          target:
            entity_id: light.storage_lights
          data:
            brightness_step_pct: -20
            transition: 1
        - delay:
            seconds: 1
      until:
        - condition: state
          entity_id: input_boolean.dim_state_storage_stop
          state: "on"

- alias: 'Smart button storage dim up'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_boolean.dim_state_storage_stop
      from: "on"
      to: "off"
  condition:
    condition: state
    entity_id: input_boolean.dim_state_storage_up
    state: 'on'
  action:
    repeat:
      sequence:
        - service: light.turn_on
          target:
            entity_id: light.storage_lights
          data:
            brightness_step_pct: 20
            transition: 1
        - delay:
            seconds: 1
      until:
        - condition: state
          entity_id: input_boolean.dim_state_storage_stop
          state: "on"

- alias: 'Smart button storage start dim'
  initial_state: 'on'
  trigger:
  - device_id: f2855c5523ee662303b3e106f4575abb
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: turn_on
  action:
    service: input_boolean.turn_off
    data_template:
      entity_id: input_boolean.dim_state_storage_stop

- alias: 'Smart button storage stop dim'
  initial_state: 'on'
  trigger:
  - device_id: f2855c5523ee662303b3e106f4575abb
    domain: zha
    platform: device
    type: remote_button_long_release
    subtype: turn_on
  action:
    - service: python_script.toggle_bool
      data_template:
        entity_id: input_boolean.dim_state_storage_up
    - service: input_boolean.turn_on
      data_template:
        entity_id: input_boolean.dim_state_storage_stop
