alias: 'Smart button bedroom'
initial_state: 'on'
trigger:
- device_id: 63d4d6c2bfe5f91ea76d24dd6f1e3e05
  domain: deconz
  platform: device
  type: remote_button_short_press
  subtype: turn_on
action:
  service: light.toggle
  entity_id:
    - light.bedroom
