# - alias: 'Smart button bedroom test'
#   initial_state: 'on'
#   trigger:
#   - device_id: 63d4d6c2bfe5f91ea76d24dd6f1e3e05
#     domain: deconz
#     platform: device
#     type: remote_button_short_release
#     subtype: turn_on
#   action:
#     service: python_script.toggle_bool
#     data_template:
#       entity_id: input_boolean.button_test

- alias: 'Smart button bedroom'
  initial_state: 'on'
  trigger:
  - device_id: 34f62b3628803a3e0f2e8be56c7c0ea1
    domain: zha
    platform: device
    type: remote_button_short_release
    subtype: turn_on
  action:
    service: light.toggle
    target:
      entity_id: light.bedroom_lights

- alias: 'Smart button office'
  initial_state: 'on'
  trigger:
  - device_id: f2855c5523ee662303b3e106f4575abb
    domain: zha
    platform: device
    type: remote_button_short_release
    subtype: turn_on
  action:
    service: light.toggle
    target:
      entity_id: light.office_lights

- alias: 'Smart button living room'
  initial_state: 'on'
  trigger:
  - device_id: 5261e7eb63a15f71a968984f20840eda
    domain: zha
    platform: device
    type: remote_button_short_release
    subtype: turn_on
  action:
    service: light.toggle
    target:
      entity_id: light.living_room_lights
