alias: 'Smart button bathroom'
initial_state: 'on'
trigger:
- device_id: a277bb05e8c0605375710af00b42972f
  domain: deconz
  platform: device
  type: remote_button_short_press
  subtype: turn_on
action:
  service: light.toggle
  entity_id:
    - light.bathroom
