alias: 'Turn lights off when my devices are offline'
initial_state: 'on'
trigger:
  platform: state
  entity_id: person.val
  to: not_home
action:
  service: light.turn_off
  entity_id:
    - light.bedroom
    - light.living_room
