alias: 'Turn lights on when my devices are in home zone'
initial_state: 'on'
trigger:
  platform: state
  entity_id: person.val
  to: home
action:
  service: light.turn_on
  entity_id:
    - light.bedroom
    - light.living_room
    - light.bathroom
