- alias: 'New HomeAssistant version'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.home_assistant_website_update_available
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.enable_version_notification
    state: 'on'
  action:
    service: notify.mobile_app_oneplus_nord_n10
    data:
      title: "New HomeAssistant version"
      message: "There is a new HomeAssistant release available. Newest version is: {{ states('sensor.home_assistant_website') }}"
