alias: 'Increase brightness of lamp from dimmer'
initial_state: 'on'
trigger:
  platform: template
  value_template: "{{ states('sensor.time') == states('sensor.wakeup_start_time_lights') }}"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.wakeup
      state: 'on'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.wakeup_weekends
          state: 'on'
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
action:
  service: shell_command.wakeup_light_call
# Would be nicer but does not work because one can't use templating in "data" :/
#      - service: deconz.configure
#        data:
#          entity: light.bedroom
#          field: '/state'
#          data:
#            'on': true
#            'bri': {{ states('input_number.wakeup_final_brightness') }} <- make hass go into safe mode
#            'transitiontime': 50
