- alias: 'Increase brightness of lamp from dimmer'
  initial_state: 'on'
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == states('sensor.wakeup_start_time_lights') }}"
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: input_boolean.wakeup_only_when_home
          state: 'off'
        - condition: and
          conditions:
          - condition: state
            entity_id: person.val
            state: 'home'
          - condition: state
            entity_id: input_boolean.wakeup_only_when_home
            state: 'on'
      - condition: state
        entity_id: input_boolean.wakeup
        state: 'on'
      - condition: or
        conditions:
          - condition: state
            entity_id: input_boolean.wakeup_weekends
            state: 'on'
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
  action:
      service: light.turn_on
      target:
        entity_id: light.bedroom_lights
      data:
        brightness: "{{ states('input_number.wakeup_final_brightness') | int }}"
        transition: "{{ ( states('input_number.wakeup_duration') | int ) * 60 }}"
